package com.project.repositories;

import com.project.models.Patient;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface PatientRepository extends JpaRepository<Patient, Long> {
    // Basic CRUD operations are auto-generated by Spring Data JPA
    
    // Example custom query (optional):
    // List<Patient> findByNameContainingIgnoreCase(String name);
}
